services:
    web:
        image: compilada:02
        build:
            context: ./
        expose:
            - "80"
        ports:
            - "80:80"
        command:
            python3.10 /myapp/app.py